Try to fix missing types.Union by using python 3.9
Error is yet again in "sphinx/util/typing.py":
  ImportError: cannot import name 'Union' from 'types'...