Try to fix missing 'numba.generated_jit' using python 3.8
Error is in "clifford/_numba_utils.py":
  AttributeError: module 'numba' has no attribute 'generated_jit'